# Console dimensions
SCREEN_WIDTH = 180
SCREEN_HEIGHT = 100
MAP_WIDTH = SCREEN_WIDTH
MAP_HEIGHT = int(0.7 * SCREEN_HEIGHT)
GUI_WIDTH = SCREEN_WIDTH
GUI_HEIGHT = SCREEN_HEIGHT - MAP_HEIGHT

# GUI dimensions
BORDER_WIDTH = 5
BAR_WIDTH = GUI_WIDTH/2 - 2*BORDER_WIDTH
BAR_HEIGHT = int(0.1 * GUI_HEIGHT)
MSG_WIDTH = GUI_WIDTH / 2
MSG_HEIGHT = GUI_HEIGHT - BORDER_WIDTH

# Room data
ROOM_MAX_SIZE = 25
ROOM_MIN_SIZE = 5
MAX_ROOMS = 50
MAX_MOBS = 3

# FOV
FOV = 0
FOV_LIT_WALLS = True
LIGHT_RANGE = 10
