# Consts
SCREEN_WIDTH = 180
SCREEN_HEIGHT = 100
MAP_WIDTH = SCREEN_WIDTH
MAP_HEIGHT = int(0.7 * SCREEN_HEIGHT)
GUI_WIDTH = SCREEN_WIDTH
GUI_HEIGHT = SCREEN_HEIGHT - MAP_HEIGHT
BAR_WIDTH = GUI_WIDTH / 2
BAR_HEIGHT = int(0.1 * GUI_HEIGHT)

# Room data
ROOM_MAX_SIZE = 25
ROOM_MIN_SIZE = 5
MAX_ROOMS = 50
MAX_MOBS = 3

# FOV
FOV = 0
FOV_LIT_WALLS = True
LIGHT_RANGE = 10
